---
- name: stop and disable zookeeper service
  systemd:
    name: zookeeper
    state: stopped
    enabled: no
  ignore_errors: yes

- name: "remove zookeeper directory {{ item }}"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ zookeeper_home }}"
    - "{{ zookeeper_release_root }}"
    - "{{ zookeeper_data_dir }}"
    - "{{ zookeeper_logs_dir }}"
    - "{{ zookeeper_pid_file | dirname }}"

- name: remove jmx_exporter
  file:
    path: "{{ jmx_exporter_home }}"
    state: absent

- name: reload systemd
  systemd:
    daemon_reload: yes
