---
- name: Update soft open files
  pam_limits:
    domain: "{{ zookeeper_user }}"
    limit_type: 'soft'
    limit_item: nofile
    value: "{{ zookeeper_open_files }}"
    comment: Zookeeper soft open files

- name: Update hard open files
  pam_limits:
    domain: "{{ zookeeper_user }}"
    limit_type: 'hard'
    limit_item: nofile
    value: "{{ zookeeper_open_files }}"
    comment: Zookeeper hard open files

- name: Update soft max processes
  pam_limits:
    domain: "{{ zookeeper_user }}"
    limit_type: 'soft'
    limit_item: nproc
    value: "{{ zookeeper_nproc }}"
    comment: Zookeeper soft max processes

- name: Update hard max processes
  pam_limits:
    domain: "{{ zookeeper_user }}"
    limit_type: 'hard'
    limit_item: nproc
    value: "{{ zookeeper_nproc }}"
    comment: Zookeeper hard max processes

- name: Update vm.swappiness
  sysctl:
    name: vm.swappiness
    value: 1
    state: present

- name: Update fs.file-max
  sysctl:
    name: fs.file-max
    value: 1000000
    state: present
    sysctl_set: yes

- name: Update fs.nr_open
  sysctl:
    name: fs.nr_open
    value: 1000000
    state: present
    sysctl_set: yes
